[package]
name = "badpod"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.22"
regex = "1.6.0"
serde = { version = "1.0.145", features = ["derive"] }
strum = "0.24.1"
strum_macros = "0.24.3"
time = { version = "0.3.15", features = ["serde-well-known"] }
xml_serde = "1.4.1"

[dev-dependencies]
pretty_assertions = "1.3.0"
