[package]
authors = ["RSS Blue", "Dovydas Joksas"]
categories = ["parsing"]
description = "A Rust crate for working with imperfect feeds of podcasts."
edition = "2021"
keywords = ["podcast", "rss", "xml"]
license = "MIT"
name = "badpod"
readme = "README.md"
repository = "https://github.com/rssblue/badpod"
version = "0.2.3"

[dependencies]
chrono = "0.4.22"
regex = "1.6.0"
serde = { version = "1.0.145", features = ["derive"] }
strum = "0.24.1"
strum_macros = "0.24.3"
time = { version = "0.3.15", features = ["serde-well-known"] }
xml_serde = "1.4.1"

[dev-dependencies]
pretty_assertions = "1.3.0"

[lib]
doctest = false
